name: Events Demo 1
# on: [push, workflow_dispatch]
# for filters
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*' # any branch name that has name dev in it
      - 'feat/**' #any branch name that has name feat in it n any special characters too
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."